# Help:  https://aka.ms/yaml

resources:
- repo: self

variables:  []

trigger:
- master

stages:
  - stage:  build
    dependsOn:  []
    variables:  []
    jobs:
    - job:  main
      dependsOn:  []
      variables:  []
      continueOnError:  false
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - script:  ls -l
      # Deploy Master ARM template from artefact files
      - task: AzureResourceGroupDeployment@2
        displayName: Azure Deployment - Master
        inputs:
          azureSubscription: shared-infra
          resourceGroupName: $(rg)
          location: '$(location)'
          templateLocation:  Linked artifact
          csmFile: deploy-scripts/dns.json
          csmParametersFile: deploy-scripts/dns.parameters.json
        timeoutInMinutes: 3
