# Help:  https://aka.ms/yaml

resources:
- repo: self

variables:  []

trigger:
- master

stages:
  - stage:  build
    dependsOn:  []
    variables:  []
    jobs:
    - job:  main
      dependsOn:  []
      variables:  []
      continueOnError:  false
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      # Publish "deploy-scripts" artefact
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: deploy-scripts'
        inputs:
          PathtoPublish: .
          ArtifactName: deploy-scripts
  - stage:  release
    dependsOn:  build
    variables: []
    jobs:
    - job:  main
      dependsOn:  []
      variables:
        location: eastus
        rg: vpl-dns
      pool:
        vmImage: ubuntu-latest
      steps:
      # Don't checkout repo
      - checkout: none
      # Download deploy-scripts artefact from previous stage
      - download: current
        artifact: deploy-scripts
      # Deploy Master ARM template from artefact files
      - task: AzureResourceGroupDeployment@2
        displayName: Azure Deployment - Master
        inputs:
          azureSubscription: shared-infra
          resourceGroupName: $(rg)
          location: '$(location)'
          templateLocation:  Linked artifact
          csmFile: $(Pipeline.Workspace)/deploy-scripts/dns.json
          csmParametersFile: $(Pipeline.Workspace)/deploy-scripts/dns.parameters.json
        timeoutInMinutes: 3
